CREATE TABLE IF NOT EXISTS TEMPERATURE(TIMESTAMP DATETIME, VALUE FLOAT);
CREATE TABLE IF NOT EXISTS HUMIDITY(TIMESTAMP DATETIME, VALUE FLOAT);
CREATE TABLE IF NOT EXISTS WEIGHT(TIMESTAMP DATETIME, VALUE FLOAT);
